version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - ./main.py:/app/main.py
      - ./uploads:/uploads
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
